-- 코드를 작성해주세요
SELECT C.ID, 
(CASE
    WHEN C.PERCENTAGE <= 25 THEN 'CRITICAL'
    WHEN C.PERCENTAGE <= 50 AND C.PERCENTAGE > 25 THEN 'HIGH'
    WHEN C.PERCENTAGE <= 75 AND C.PERCENTAGE > 50 THEN 'MEDIUM'
    ELSE 'LOW'
END) AS 'COLONY_NAME'
FROM (
    SELECT 
        A.ID, 
        B.COLONY_RANK, 
        (B.COLONY_RANK / (SELECT COUNT(*) FROM ECOLI_DATA)) * 100 AS PERCENTAGE
    FROM 
        ECOLI_DATA AS A
    JOIN (
        SELECT 
            ID, 
            RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_RANK
        FROM 
            ECOLI_DATA
    ) AS B ON A.ID = B.ID
    GROUP BY 
        A.ID, 
        B.COLONY_RANK) AS C
ORDER BY C.ID